Broadway_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 

handler404 = "commons.views.not_found_404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("commons/", include("commons.urls")),
    path('crud/', include('crud.urls')),
    path("accounts/", include("accounts.urls")),
    path("quiz/", include("quiz.urls")),
    path("classbased/", include("classbased.urls", namespace="classbased")),
    path("api/", include("api.urls", namespace="api")),
    path("", include("myapp.urls")), # URL Chaining
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from . import views

app_name = "api"

router = DefaultRouter()

router.register("viewset/classroom", views.ClassRoomViewSet, basename="classroom")
router.register("viewset/student", views.StudentViewSet, basename="student")
router.register("viewset/user", views.UserViewSet, basename="user")

urlpatterns = [
    path("student/", views.StudentView.as_view(), name="student"),
    path("student/<int:id>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("classroom/", views.ClassRoomView.as_view(), name="classroom"),
    path("classroom/<int:id>/", views.ClassRoomView.as_view(), name="classroom_patch"),
    path("login/", obtain_auth_token),
    path("login/", views.LoginAPIView.as_view()),
] + router.urls


using_serializer_paths = [
    path('classroom-using-serializer/<int:id>/', views.ClassRoomUsingSerializerDetailView.as_view()),
    path("using-serializer/classroom/", views.ClassRoomUsingSerializerView.as_view()),
    path("using-serializer/student/", views.StudentUsingSerializerView.as_view()),
]

using_model_serializer_paths = [
    path("using-model-serializer/student/", views.StudentUsingModelSerView.as_view())
]

generic_urls = [
    path("generic/classroom-list/", views.ClassRoomGenericListView.as_view()),
    path("generic/classroom-create/", views.ClassRoomGenericCreateView.as_view()),
    path("generic/classroom/", views.ClassRoomGenericView.as_view()),
    path("generic/classroom-update/<int:pk>/", views.ClassRoomGenericUpdateView.as_view()),
    path("generic/classroom-detail/<int:pk>/", views.ClassRoomGenericDetailView.as_view()),
    path("generic/classroom-delete/<int:pk>/", views.ClassRoomGenericDeleteView.as_view()),
    path("generic/student/<int:pk>/", views.StudentUpdateRetrieveDestroyView.as_view())
]

urlpatterns += using_serializer_paths + using_model_serializer_paths + generic_urls

classbased/urls.py
from django.urls import path
from . import views

app_name = "classbased"

urlpatterns = [
    path("classroom/", views.ClassRoomView.as_view(), name="classroom"),
    # path("classroom/", views.ClassroomListCreateView.as_view(), name="classroom"),
    path("classroom-update/<int:pk>/", views.ClassroomUpdateView.as_view(), name="classroom_update"),
    path("classroom-delete/<int:pk>/", views.ClassroomDeleteView.as_view(), name="classroom_delete"),
    path("student/", views.StudentListView.as_view(), name="student"),
    path("student-create/", views.StudentCreateView.as_view(), name="student_create"),
    path("student-detail/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("student-update/<int:pk>/", views.StudentUpdateView.as_view(), name="student_update"),

    path("api/student/<int:id>/", views.student_detail_api_view),
    path("student/consuming-api/", views.StudentConsumingView.as_view(), name="student_consuming_api"),
    path("", views.HomeView.as_view(), name="home"),
]

classbased/models.py
from django.db import models

# Create your models here.

crud/models.py
from django.db import models

# Create your models here.
class ClassRoom(models.Model):
    name=models.CharField(max_length=20)
  
    def __str__(self):
        return self.name
    
class Student(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, null=True, blank=True, related_name="students")
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    email=models.EmailField(max_length=20)
    address=models.CharField(max_length=50)


    def __str__(self):
        return f"Student {self.name}"
    

    
class StudentProfile(models.Model): # default related name is "studentprofile"
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    phone = models.CharField(max_length=14)
    bio = models.TextField(max_length=500)
    profile_picture = models.FileField(null=True, blank=True, upload_to="profile_picture")
    
    def __str__(self):
        return f"Profile of {self.student.name}"

classbased/forms.py
from django import forms
from crud.models import ClassRoom, Student


class ClassRoomForm(forms.Form):
    name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'class name'}))


class ClassRoomModelForm(forms.ModelForm):
    class Meta:
        model = ClassRoom
        fields = ["name"]   # "__all__" is used to add all fields


class StudentModelForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=14)
    bio = forms.CharField(widget=forms.Textarea(attrs={"rows": 4}))
    profile_picture = forms.FileField(required=False)

    class Meta:
        model = Student
        fields = ["name", "age", "email", "address", "classroom"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

classbased/views.py
import requests
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from crud.models import ClassRoom, Student, StudentProfile
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views import View
from django.contrib import messages
from .forms import ClassRoomForm, ClassRoomModelForm, StudentModelForm


class HomeView(TemplateView):
    template_name = "classbased/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # dictionary
        context["name"] = "Hary"
        return context

    def get(self, *args, **kwargs):
        import json
        user = self.request.user
        with open("crud/counter.json", "r") as fp:
            data = fp.read()
            data = json.loads(data)
        data['crud_student_counter'] += 1
        with open("crud/counter.json", "w") as fp:
            data = json.dumps(data)
            fp.write(data)

        return super(HomeView, self).get(*args, **kwargs)


class ClassRoomView(ListView):
    template_name = "classbased/classroom.html"
    context_object_name = "classrooms"
    paginate_by = 4

    def get_queryset(self):
        filters = {}
        search = self.request.GET.get("search")
        if search:
            filters.update(name__istartswith=search)
        return ClassRoom.objects.filter(**filters)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # form = ClassRoomForm()
        form = ClassRoomModelForm()
        context["form"] = form
        return context

    def post(self, *args, **kwargs):
        form = ClassRoomModelForm(self.request.POST)  # We are validating user input data
        if form.is_valid():
            print(form.cleaned_data)  # form.cleaned is a dict type
            # name = form.cleaned_data["name"]
            # ClassRoom.objects.create(name=name)
            form.save()
            messages.success(self.request, "Classroom added successfully !")
        else:
            messages.error(self.request, "Invalid Form data")
        return redirect("classbased:classroom")


class ClassroomListCreateView(CreateView):
    queryset = ClassRoom.objects.all()  # querysets are lazy in Django
    template_name = "classbased/classroom.html"
    form_class = ClassRoomModelForm
    success_url = reverse_lazy("classbased:classroom")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["classrooms"] = self.get_queryset()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            messages.success(request, "Classroom added successfully !")
            return self.form_valid(form)
        else:
            messages.error(request, "Something went wrong !")
            return self.form_invalid(form)


class ClassroomUpdateView(UpdateView):
    queryset = ClassRoom.objects.all()
    template_name = "classbased/classroom_update.html"
    form_class = ClassRoomModelForm
    context_object_name = "classroom"
    success_url = reverse_lazy("classbased:classroom")


class ClassroomDeleteView(DeleteView):
    queryset = ClassRoom.objects.all()
    template_name = "classbased/classroom_delete.html"
    success_url = reverse_lazy("classbased:classroom")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            messages.success(self.request, "Classroom deleted successfully !")
            return self.form_valid(form)  # deletes the classroom
        else:
            messages.error(self.request, "Something went wrong !")
            return self.form_invalid(form)


class StudentListView(ListView):
    queryset = Student.objects.all()
    template_name = "classbased/student.html"


class StudentCreateView(CreateView):
    model = Student
    template_name = "classbased/student_create.html"
    form_class = StudentModelForm
    success_url = reverse_lazy("classbased:student")
    next_form = ClassRoomModelForm

    def form_valid(self, form):
        self.object = form.save()
        student = self.object
        bio = form.cleaned_data['bio']
        phone = form.cleaned_data["phone_number"]
        StudentProfile.objects.create(student=student, bio=bio, phone=phone)
        messages.success(self.request, "Student added successfully !")
        return redirect("classbased:student")

    def form_invalid(self, form):
        messages.error(self.request, "Could not create student!")
        return super().form_invalid(form)


class StudentDetailView(DetailView):
    queryset = Student.objects.all()
    template_name = "classbased/student_detail.html"
    context_object_name = "student"


class StudentUpdateView(UpdateView):
    queryset = Student.objects.all()
    template_name = "classbased/student_update.html"
    form_class = StudentModelForm

    # success_url = reverse_lazy("classbased:student_detail")

    def get_success_url(self):
        return reverse_lazy("classbased:student_detail", self.get_object().id)

    def get_initial(self):
        student = self.get_object()
        initial = super().get_initial()
        try:
            profile = StudentProfile.objects.get(student=student)
        except:
            pass
        else:
            initial["bio"] = profile.bio
            initial["phone_number"] = profile.phone
            initial["profile_picture"] = profile.profile_picture
        return initial

    def form_valid(self, form):
        bio = form.cleaned_data.pop("bio")
        phone_number = form.cleaned_data.pop("phone_number")
        pp = form.cleaned_data.pop("profile_picture")
        student = form.save()
        # (<sp_object>, False)
        sp, _ = StudentProfile.objects.update_or_create(student=student,
                                                        defaults={"bio": bio, "phone": phone_number})
        if pp:
            sp.profile_picture = pp
            sp.save()
        return redirect("classbased:student_detail", student.id)


def student_detail_api_view(request, id):
    try:
        student = Student.objects.get(id=id)
    except:
        return JsonResponse({"detail": "Not Found"})
    response = {
        "name": student.name,
        "age": student.age,
        "email": student.email,
        "address": student.address
    }
    return JsonResponse(response)


class StudentConsumingView(View):
    def get(self, *args, **kwargs):
        url = "http://localhost:8000/api/viewset/student/"
        response = requests.get(url)
        if response.status_code in [200, "200"]:
            response = response.json()
            students = response if type(response) == list else response["results"]
            return render(self.request, template_name="classbased/student_consuming_api.html",
                          context={"students": students})
        return redirect("root_page")

classbased/templates/classbased/classroom.html
{% extends "commons/layouts/base.html" %}

{% block title %}Classroom{% endblock %}

{% block content %}
    {% include 'classbased/includes/nav.html' %}
    <br>
    <div class="container">
        <h2>Classroom</h2>
        <br>
        <form method="post" class="form-control">
            {% csrf_token %}
            {{ form }}<br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for class in classrooms %}
                <tr>
                    <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                    <td>{{ class.name }}</td>
                    <td>
                        <a href="{% url 'classbased:classroom_update' class.pk %}" class="btn btn-primary">Update</a>
                        <a href="{% url 'classbased:classroom_delete' class.pk %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if is_paginated %}
            <nav aria-label="..." style="float: right">
            <ul class="pagination">
                {% if request.GET.page and request.GET.page > "1" %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                {% endif %}
                {% if request.GET.page == "1" or not request.GET.page %}
                    <li class="page-item active"><a class="page-link" href="?page=1">1</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                {% endif %}
                {% if request.GET.page == "2" %}
                    <li class="page-item active"><a class="page-link" href="?page=2">2</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page=2">2</a></li>
                {% endif %}
                {% if request.GET.page == "3" %}
                    <li class="page-item active"><a class="page-link" href="?page=3">3</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page=3">3</a></li>
                {% endif %}
                <li class="page-item">
                    {% if page_obj.has_next %}
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    {% else %}
                        <a class="page-link disabled" href="#">Next</a>
                    {% endif %}
                </li>
            </ul>
            <div style="text-align: right">
                <small>{% if request.GET.page %}
                    {{ request.GET.page }} of {{ page_obj.paginator.num_pages }} pages
                {% else %}
                    1 of {{ page_obj.paginator.num_pages }} pages
                {% endif %}</small>
            </div>
        {% endif %}
        </nav>
    </div>
{% endblock %}

classbased/templates/classbased/classroom_delete.html
{% extends "commons/layouts/base.html" %}

{% block title %}
    Classroom Delete
{% endblock %}
{% block content %}
    {% include "classbased/includes/nav.html"%}
    <br>
    <div class="cointainer">
        <h2>Classroom delete</h2>
        <h3>Are you sure want to delete classroom {{ object.name }}</h2>
        <br>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Submit</button>
        </form>
    </div>
{% endblock %}
        

classbased/templates/classbased/classroom_update.html
{% extends 'commons/layouts/base.html' %}

{% block title %}
     Classroom Update
{% endblock %}

{% block content %}
    {% include 'classbased/includes/nav.html' %}
    <br>
    <h2>Classroom Update</h2>
    <div class="cointainer">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <br>
            <button type = "submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

classbased/templates/classbased/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
    <h1>Classbased home page</h1>
    <h2>Hello i am {{ name }} </h2>
</body>
</html>

classbased/templates/classbased/student.html
{% extends "commons/layouts/base.html" %}

{% block title %}
    Student
{% endblock %}

{% block content %}
    {% include "classbased/includes/nav.html" %}
    <br>
    <div class="container">
        <a href="{% url 'classbased:student_create' %}" style="float: right" class="btn btn-success">Add Student</a>
        <h2>Student</h2>
        <br>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Classroom</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for student in student_list   %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ student.name }}</td>
                    <td>{{ student.age }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.address }}</td>
                    <td>
                        {% if student.classroom %}
                            {{ student.classroom.name }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'classbased:student_detail' student.id %}" class="btn btn-primary">Detail</a>
                        <a href="#" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

classbased/templates/classbased/student_consuming_api.html
{% extends 'commons/layouts/base.html' %}

{% block title %}Student Consuming API{% endblock %}

{% block content %}
    <div class="container">
    
    <table class="table table-striped">
        <thead>
        <tr>
            <th>S.N</th>
            <th>Name</th>
            <th>Age</th>
            <th>Email</th>
            <th>Address</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.addres }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

classbased/templates/classbased/student_create.html
{% extends 'commons/layouts/base.html' %}

{% block title %}
    Add Student
{% endblock %}

{% block content %}
    {% include 'classbased/includes/nav.html' %}
    <br>
    <div class="container">
        <h2>Add Student</h2>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group" style="width: 50%">
            {{ form }}
        </div>
        <br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    </div>
{% endblock %}

classbased/templates/classbased/student_detail.html
{% extends "commons/layouts/base.html" %}
{% load static %}

{% block title %}
    Student Detail
{% endblock %}

{% block content %}
    {% include 'classbased/includes/nav.html' %}
    <br>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-md-4">
                {% if student.studentprofile.profile_picture %}
                    <img src="{{ student.studentprofile.profile_picture.url }}" alt="profile_picture" style="height: 300px;width: 300px;">
                {% else %}
                <img src="{% static 'crud/default.png' %}" style="height: 300px;width: 300px;" alt="profile_picture">
                {% endif %}
            </div>
            <div class="col-md-8">
                <h2>Student Detail</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Name</td>
                        <td>{{ student.name }}</td>
                    </tr>
                    <tr>
                        <td>Age</td>
                        <td>{{ student.age }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ student.email }}</td>
                    </tr>
                    <tr>
                        <td>Address</td>
                        <td>{{ student.address }}</td>
                    </tr>
                    <tr>
                        <td>Classroom</td>
                        <td>{{ student.classroom.name | title }}</td>
                    </tr>
                    <tr>
                        <td>Phone Number</td>
                        <td>{{ student.studentprofile.phone }}</td>
                    </tr>
                    <tr>
                        <td>Bio</td>
                        <td>{{ student.studentprofile.bio }}</td>
                    </tr>
                </table>
                <a href="{% url 'classbased:student_update' student.id %}" class="btn btn-primary">Update</a>
                <a href="{% url 'classbased:student' %}" class="btn btn-outline-success">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

classbased/templates/classbased/student_update.html
{% extends "commons/layouts/base.html" %}
{% load static %}

{% block title %}
    Student Update
{% endblock %}

{% block content %}
    {% include "classbased/includes/nav.html" %}
    <br><br>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    {% if student.studentprofile.profile_picture %}
                        <img src="{{ student.studentprofile.profile_picture.url }}" style="height: 300px; width: 300px"
                             alt="profile_picture">
                    {% else %}
                        <img src="{% static 'crud/default.png' %}" style="height: 300px; width: 300px"
                             alt="profile_picture">
                    {% endif %}
                    <br>
{#                <input type="file" name="profile_picture" accept=".png, .jpg, .jpeg">#}
{#                    {% if student.studentprofile.profile_picture %}#}
{#                        <a href="{{ student.studentprofile.profile_picture.url }}" target="_blank">{{ student.studentprofile.profile_picture }}</a>#}
{#                        <input type="checkbox" name="pp_clear" id="profile_picture-clear_id">#}
{#                        <label for="profile_picture-clear_id">Clear</label></span><br>#}
{#                    {% endif %}#}
                </div>
                <div class="col-md-8">
                    <h2>Student Update</h2>
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'classbased:student_detail' student.id %}" class="btn btn-outline-primary">Back</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}