Broadway_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 

handler404 = "commons.views.not_found_404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("commons/", include("commons.urls")),
    path('crud/', include('crud.urls')),
    path("accounts/", include("accounts.urls")),
    path("quiz/", include("quiz.urls")),
    path("classbased/", include("classbased.urls", namespace="classbased")),
    path("api/", include("api.urls", namespace="api")),
    path("", include("myapp.urls")), # URL Chaining
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from . import views

app_name = "api"

router = DefaultRouter()

router.register("viewset/classroom", views.ClassRoomViewSet, basename="classroom")
router.register("viewset/student", views.StudentViewSet, basename="student")
router.register("viewset/user", views.UserViewSet, basename="user")

urlpatterns = [
    path("student/", views.StudentView.as_view(), name="student"),
    path("student/<int:id>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("classroom/", views.ClassRoomView.as_view(), name="classroom"),
    path("classroom/<int:id>/", views.ClassRoomView.as_view(), name="classroom_patch"),
    path("login/", obtain_auth_token),
    path("login/", views.LoginAPIView.as_view()),
] + router.urls


using_serializer_paths = [
    path('classroom-using-serializer/<int:id>/', views.ClassRoomUsingSerializerDetailView.as_view()),
    path("using-serializer/classroom/", views.ClassRoomUsingSerializerView.as_view()),
    path("using-serializer/student/", views.StudentUsingSerializerView.as_view()),
]

using_model_serializer_paths = [
    path("using-model-serializer/student/", views.StudentUsingModelSerView.as_view())
]

generic_urls = [
    path("generic/classroom-list/", views.ClassRoomGenericListView.as_view()),
    path("generic/classroom-create/", views.ClassRoomGenericCreateView.as_view()),
    path("generic/classroom/", views.ClassRoomGenericView.as_view()),
    path("generic/classroom-update/<int:pk>/", views.ClassRoomGenericUpdateView.as_view()),
    path("generic/classroom-detail/<int:pk>/", views.ClassRoomGenericDetailView.as_view()),
    path("generic/classroom-delete/<int:pk>/", views.ClassRoomGenericDeleteView.as_view()),
    path("generic/student/<int:pk>/", views.StudentUpdateRetrieveDestroyView.as_view())
]

urlpatterns += using_serializer_paths + using_model_serializer_paths + generic_urls

classbased/urls.py
from django.urls import path
from . import views

app_name = "classbased"

urlpatterns = [
    path("classroom/", views.ClassRoomView.as_view(), name="classroom"),
    # path("classroom/", views.ClassroomListCreateView.as_view(), name="classroom"),
    path("classroom-update/<int:pk>/", views.ClassroomUpdateView.as_view(), name="classroom_update"),
    path("classroom-delete/<int:pk>/", views.ClassroomDeleteView.as_view(), name="classroom_delete"),
    path("student/", views.StudentListView.as_view(), name="student"),
    path("student-create/", views.StudentCreateView.as_view(), name="student_create"),
    path("student-detail/<int:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("student-update/<int:pk>/", views.StudentUpdateView.as_view(), name="student_update"),

    path("api/student/<int:id>/", views.student_detail_api_view),
    path("student/consuming-api/", views.StudentConsumingView.as_view(), name="student_consuming_api"),
    path("", views.HomeView.as_view(), name="home"),
]

myapp/urls.py
from django.urls import path
from .views import home, home_detail, portfolio, test, root_page, learning_context, using_bootstrap
urlpatterns=[
    path("home/<int:id>/detail/", home_detail, name="home_details"),
    path("test/", test, name="test"),
    path("portfolio/", portfolio, name="portfolio"),
    path("learning-context/", learning_context, name="learning_context"),
    path("using_bootstrap/", using_bootstrap, name="using_bootstrap"),
    path("", root_page, name="root_page"),
    path("", home),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    query_strings = request.GET 
    name = query_strings.get("name")
    print(name)
    print(request.scheme)
    print(request.method)
    print(request.user)
    print(request.get_full_path())
    return HttpResponse(f"Hello world. I am {name}")

def home_detail(request,id):
    return HttpResponse(f'<h1>My home id is {id}')

def portfolio(request):
    return render(request, template_name="myapp/portfolio.html")

def test(request):
    return render(request, template_name="myapp/test.html")

def root_page(request):
    return render(request, template_name="myapp/root_page.html")

def learning_context(request):
    student = {"name": "Nabraj", "age": 21, "email": "nabrajmadai21@email.com", "address": "MNR"}
    students = [
       {"name": "Nabs", "age": 25, "email": "nabs24@email.com", "address": "MNR"},
       {"name": "Navya", "age": 18, "email": "navya@email.com", "address": "MNR"},
       {"name": "Rolex", "age": 20, "email": "rolex21@email.com", "address": "MNR"},
       {"name": "Nabraj...", "age": 28, "email": "nabs@email.com", "address": "MNR"},
    ]
    return render(request, template_name="myapp/learning_context.html", context={"students": students, "student": student})

def using_bootstrap(request):
    students = [
       {"name": "Nabs", "age": 25, "email": "nabs24@email.com", "address": "MNR"},
       {"name": "Navya", "age": 18, "email": "navya@email.com", "address": "MNR"},
       {"name": "Rolex", "age": 20, "email": "rolex21@email.com", "address": "MNR"},
       {"name": "Nabraj...", "age": 28, "email": "nabs@email.com", "address": "MNR"},
    ]
    return render(request, template_name="myapp/using_bs.html", context={"student": students })

myapp/templates/myapp/learning_context.html
<!DOCTYPE html>
<html lang= "eng">
<head>
    <meta charset="UTF-8">
    <title>Context</title>
</head>
<body>
    Name: {{student.name}}<br>
    Age: {{student.age}}<br>
    Email: {{student.email}}<br>
    Address: {{student.address}}
    <br><br><br>
{% for s in students %} 
Name: {{s.name}}<br>
Age: {{s.age}}<br>
Email: {{s.email}}<br>
Address: {{s.address}}<br><br>

{% endfor %}
    {{ students.0.name}}
</body>
</html>

myapp/templates/myapp/root_page.html
<!DOCTYPE html>
<html lang= "eng">
<head>
    <meta charset="UTF-8">
    <title>Root page</title>
</head>
<body align="center">
    <h1>Root page<h1>
    <div>
        <h2>
            <a href="{% url 'portfolio' %}">Portfolio</a><br><br>
            <a href="{% url 'learning_context' %}">Context</a><br><br>
            <a href="{% url 'using_bootstrap' %}">Using Bootstrap</a><br><br>
            <a href="{% url 'commons_student' %}">Template Inheritance</a><br><br>
            <a href="{% url 'crud_student' %}">CRUD</a><br><br>
            <a href="{% url 'quiz_home' %}">Quiz</a><br><br>
            <a href="{% url 'classbased:classroom' %}">Classbased</a><br><br>
            <a href="{% url 'classbased:student_consuming_api' %}">Consuming API</a>
        </h2>
    </div>
</body>
</html>

myapp/templates/myapp/test.html
<!DOCTYPE html>
{% load static%}
<html lang= "eng">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
     <link hrf= 
</head>

<body>
    <h1>Test page<h1>
</body>
</html>

myapp/templates/myapp/using_bs.html
<!DOCTYPE html>
<html lang= "eng">
<head>
    <meta charset="UTF-8">
    <title>Using Bootstrap</title>
    <link rel= <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
            {% for student in students %}
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
            {% endfor %}
        </tbody>
      </table>
</body>
</html>